part (a)


In [1]:
# import data into a numpy array

import numpy as np

data_array = np.genfromtxt("python_language_1_data.csv", delimiter=",", names=True,
                            dtype=[int, int, float])

data_array

array([(1937,   1, 30.226), (1937,   2, 52.832), (1937,   3, 10.668), ...,
       (2012, 364,  4.318), (2012, 365,  0.   ), (2012, 366,  0.   )],
      dtype=[('year', '<i4'), ('day_of_year', '<i4'), ('rainfall_mmday', '<f8')])

In [2]:
data_array['year']

array([1937, 1937, 1937, ..., 2012, 2012, 2012])

In [3]:
rainfall = "rainfall_mmday"
data_array[rainfall]

array([30.226, 52.832, 10.668, ...,  4.318,  0.   ,  0.   ])

In [4]:
# store end years

first_year = data_array[0][0]
last_year = data_array[-1][0]
first_year

1937

In [6]:
# create a year key for dictionary

year_tuple = tuple(range(first_year, last_year + 1))

In [7]:
# create dictionary, with year keys and empty list values
data_dic = {}

for year in year_tuple:
    data_dic[year] = []    

data_dic

{1937: [],
 1938: [],
 1939: [],
 1940: [],
 1941: [],
 1942: [],
 1943: [],
 1944: [],
 1945: [],
 1946: [],
 1947: [],
 1948: [],
 1949: [],
 1950: [],
 1951: [],
 1952: [],
 1953: [],
 1954: [],
 1955: [],
 1956: [],
 1957: [],
 1958: [],
 1959: [],
 1960: [],
 1961: [],
 1962: [],
 1963: [],
 1964: [],
 1965: [],
 1966: [],
 1967: [],
 1968: [],
 1969: [],
 1970: [],
 1971: [],
 1972: [],
 1973: [],
 1974: [],
 1975: [],
 1976: [],
 1977: [],
 1978: [],
 1979: [],
 1980: [],
 1981: [],
 1982: [],
 1983: [],
 1984: [],
 1985: [],
 1986: [],
 1987: [],
 1988: [],
 1989: [],
 1990: [],
 1991: [],
 1992: [],
 1993: [],
 1994: [],
 1995: [],
 1996: [],
 1997: [],
 1998: [],
 1999: [],
 2000: [],
 2001: [],
 2002: [],
 2003: [],
 2004: [],
 2005: [],
 2006: [],
 2007: [],
 2008: [],
 2009: [],
 2010: [],
 2011: [],
 2012: []}

In [25]:
# iterate through rows, adding rainfall data to appropriate year list of dictionary

for day in range(data_array.size):
    data_dic[data_array[day][0]] += data_array[day][2]

In [26]:
print(data_dic[1938])

[]


In [10]:
test_dic = {1:[], 2:[], 3:[]}
test_list = []
test_list += "cheese"
test_list

['c', 'h', 'e', 'e', 's', 'e']

In [11]:
test_dic[1] += test_list
test_dic

{1: ['c', 'h', 'e', 'e', 's', 'e'], 2: [], 3: []}

In [12]:
test_array = np.array([(1920, 1, 12.4), (1920, 2, 0), (1921, 3, 4.2)])
test_array

array([[1.920e+03, 1.000e+00, 1.240e+01],
       [1.920e+03, 2.000e+00, 0.000e+00],
       [1.921e+03, 3.000e+00, 4.200e+00]])

In [13]:
for day in test_array:
    print(day)

[1.92e+03 1.00e+00 1.24e+01]
[1920.    2.    0.]
[1921.     3.     4.2]


In [14]:
test_list_2 = [(1920, 1, 12.4), (1920, 2, 0), (1921, 3, 4.2)]
test_array_2 = np.array(test_list_2)
test_array_2

array([[1.920e+03, 1.000e+00, 1.240e+01],
       [1.920e+03, 2.000e+00, 0.000e+00],
       [1.921e+03, 3.000e+00, 4.200e+00]])

In [21]:
data_array.size


76.05205479452054